services:
  server:
    build:
      context: .
    command: python main.py -c ./data/social_media_usage.csv -n testing-data -t social_media_usage
    environment:
      - USER=db_user
      - HOST=host.docker.internal
      - PASSWORD=db_password
      - PORT=5433
    ports:
      - 8080:8080